# Generated by Django 4.0.3 on 2022-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health_num',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_num',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
