# Generated by Django 4.0.3 on 2022-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_alter_neighbourhood_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
